### ISSUE TITLE
Launching app just opens terminal without launching octave

### ISSUE THREAD

**Issue by cswancmu** [corbinlc/octave4android#87]
Octave worked for me fine a few months ago.

Then a few months went by.

Now when I open the Octave app, it prompts for donation and "maybe later" just deposits me in a new terminal emulator window NOT running Octave.

**Comment by nikhilkashyap** [comment]
Hi, 
Same issue on the Oneplus One. I've enough space on the storage for octave.

**Comment by corbinlc** [comment]
@cswancmu What device are you using and what version of Android are you using?  Did you recently upgrade what version of Android you were running?  If so, from what to what?

@cswancmu Can you try this APK and tell me what happens? https://www.dropbox.com/s/r81kadgkjpifr6n/octave_27.apk?dl=0

**Comment by cswancmu** [comment]
@corbinlc (first off, Huge fan and love the app)
Running Galaxy S4 with Cyanogenmod 11, which claims it's 4.4.4. Have not upgraded recently, although I do have a fun data point: If I restart and immediately run Octave, it does open Octave. But if I try to run another instance or quit and re-start, it again dumps me right to command line.

One moment regarding APK. Will let you know.

**Comment by cswancmu** [comment]
@corbinlc The new APK performs identically to the one from the app store. When it dumps to command line there is no error message; when it works exactly one time upon restarting it prints nothing besides the usual.

**Comment by corbinlc** [comment]
It launched the terminal, but ignored the initial command.  That is interesting.  Do you see a command at the top of the screen?  If so, can you hit Vol-Up+w to get it to show it and then copy and paste it?  You will probably have to move the cursor to the left (Vol-Up+a or left arrow if your keyboard has it) and do multiple copies to grab it all.

**Comment by cswancmu** [comment]
Would you believe that neither vol-up+w nor the hacker keyboard's "up" arrow produced any effect? To test the functionality of both of these, I DID run an echo command then pressed up. It did give me back the command I used. If no one else has this problem, I'm happy to start up Octave when I restart my phone and just keep it on all the time, which is what I did today. It's a kludge, but it works.

**Comment by corbinlc** [comment]
Alright.  The initial command isn't even being received.  That gives me a starting point.  

You are not the only one.  I have had a few reports related to using Cyanogenmod, but even if I hadn't there are so many users that pretty much no problem is truly unique.  If I have one report of it, I probably have many people effected.  If I have receive two reports of it, then it is pretty bad.  Let me look into how the initial command gets applied.  Maybe there is some sort of race case or maybe a ternary that does things different the 2nd time around.   

I appreciate your help so far.  I will get back to you when I have my next test APK.

Thanks!
Corbin

**Comment by corbinlc** [comment]
This tries setting the initial command in a different way.   Can you try it and tell me what you get?  Btw... this should only echo the initial command, not run it, so you will either get a command printed out or nothing.  

https://www.dropbox.com/s/06ua7bxnpbzgu4z/octave_27_echo_init_cmd.apk?dl=0

**Comment by corbinlc** [comment]
Also, can you print your environment variables and past them here?

**Comment by cswancmu** [comment]
When I run in a normal capacity, I get no result and no up-complete options.


Whem I run first-thing upon restarting, I do get a command printed. It is:
u0_a112@jfltevzw:/ $ echo "LD_PRELOAD= /data/data/com.octave/app_install/support/proot -r /data/data/com.octave/app_install/rootfs/ -v 5 -b /dev -b /proc -b /mnt -b /:/host-rootfs -b /storage/emulated/0/GNUOctave/rootfs:/noexec -b /storage/emulated/0/GNUOctave/intents:/intents -b /storage/emulated/0/GNUOctave/home:/home  -b /usbdisk -b /external_sd -b /extSdCard -b /sdcard -b /persist -b /storage -b /config -b /cache -b /acct -b /vendor -b /d -b /tombstones -b /efs -b /firmware-mdm -b /firmware -b /system -b /res -b /data /usr/bin/octave"

**Comment by corbinlc** [comment]
Can you print environment variables in both a restart case and then later on?

**Comment by cswancmu** [comment]
In the just-woke-up state:
_=/system/xbin/env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games:/system/bin:/system/xbin
LOOP_MOUNTPOINT=/mnt/obb
ANDROID_ROOT=/system
ANDROID_CACHE=/cache
SHELL=/system/bin/sh
ANDROID_DATA=/data
ANDROID_SOCKET_zygote=10
CLASSPATH=/data/data/de.robv.android.xposed.installer/bin/XposedBridge.jar
ANDROID_ASSETS=/system/app
TERM=screen
ANDROID_PROPERTY_WORKSPACE=9,0
ANDROID_BOOTLOGO=1
HOSTNAME=jfltevzw
LD_LIBRARY_PATH=
BOOTCLASSPATH=/system/framework/core.jar:/system/framework/conscrypt.jar:/system/framework/okhttp.jar:/system/framework/core-junit.jar:/system/framework/bouncycastle.jar:/system/framework/ext.jar:/system/framework/framework.jar:/system/framework/framework2.jar:/system/framework/telephony-common.jar:/system/framework/voip-common.jar:/system/framework/mms-common.jar:/system/framework/android.policy.jar:/system/framework/services.jar:/system/framework/apache-xml.jar:/system/framework/webviewchromium.jar:/system/framework/telephony-msim.jar
EMULATED_STORAGE_SOURCE=/mnt/shell/emulated
ACTUAL_HOME=/storage/emulated/0/GNUOctave/home
EMULATED_STORAGE_TARGET=/storage/emulated
TMPDIR=/tmp
ANDROID_STORAGE=/storage
MKSH=/system/bin/sh
EXTERNAL_STORAGE=/storage/emulated/legacy
LD_PRELOAD=
RANDOM=8159
ASEC_MOUNTPOINT=/mnt/asec
SECONDARY_STORAGE=/storage/sdcard1:/storage/usbdisk
USER=u0_a112
PS1=$(precmd)$USER@$HOSTNAME:${PWD:-?} $
HOME=/home
TERMINFO=/system/etc/terminfo

**Comment by cswancmu** [comment]
In the normal state:
u0_a112@jfltevzw:/ $ env
_=/system/xbin/env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games:/system/bin:/system/xbin
LOOP_MOUNTPOINT=/mnt/obb
ANDROID_ROOT=/system
ANDROID_CACHE=/cache
SHELL=/system/bin/sh
ANDROID_DATA=/data
ANDROID_SOCKET_zygote=10
CLASSPATH=/data/data/de.robv.android.xposed.installer/bin/XposedBridge.jar
ANDROID_ASSETS=/system/app
TERM=screen
ANDROID_PROPERTY_WORKSPACE=9,0
ANDROID_BOOTLOGO=1
HOSTNAME=jfltevzw
LD_LIBRARY_PATH=
BOOTCLASSPATH=/system/framework/core.jar:/system/framework/conscrypt.jar:/system/framework/okhttp.jar:/system/framework/core-junit.jar:/system/framework/bouncycastle.jar:/system/framework/ext.jar:/system/framework/framework.jar:/system/framework/framework2.jar:/system/framework/telephony-common.jar:/system/framework/voip-common.jar:/system/framework/mms-common.jar:/system/framework/android.policy.jar:/system/framework/services.jar:/system/framework/apache-xml.jar:/system/framework/webviewchromium.jar:/system/framework/telephony-msim.jar
EMULATED_STORAGE_SOURCE=/mnt/shell/emulated
ACTUAL_HOME=/storage/emulated/0/GNUOctave/home
EMULATED_STORAGE_TARGET=/storage/emulated
TMPDIR=/tmp
ANDROID_STORAGE=/storage
MKSH=/system/bin/sh
EXTERNAL_STORAGE=/storage/emulated/legacy
LD_PRELOAD=
RANDOM=19480
ASEC_MOUNTPOINT=/mnt/asec
SECONDARY_STORAGE=/storage/sdcard1:/storage/usbdisk
USER=u0_a112
PS1=$(precmd)$USER@$HOSTNAME:${PWD:-?} $
HOME=/home
TERMINFO=/system/etc/terminfo

**Comment by corbinlc** [comment]
Last one for today:  https://www.dropbox.com/s/d72qpb8xa7exoz0/octave_27_busybox_shell.apk?dl=0  Can you try this out and tell me how it behaves?  It changes 2 things, it use the shell from the busybox that I have included in my app as a helper utility instead of /system/bin/sh and it gets rid of the part of the path that points at /system/*.

**Comment by cswancmu** [comment]
It appears that yes, this one does work in all circumstances I tested. Plots plot, commands command. The output is:


BusyBox v1.20.2 (Debian 1:1.20.0-7) built-in shell (ash)
Enter 'help' for a list of built-in commands.

>
> LD_PRELOAD= /data/data/com.octave/app_install/support/proo
t -r /data/data/com.octave/app_install/rootfs/ -v -1 -b /dev
 -b /proc -b /mnt -b /:/host-rootfs -b /storage/emulated/0/G
NUOctave/rootfs:/noexec -b /storage/emulated/0/GNUOctave/int
ents:/intents -b /storage/emulated/0/GNUOctave/home:/home  -
b /usbdisk -b /external_sd -b /extSdCard -b /sdcard -b /pers
ist -b /storage -b /config -b /cache -b /acct -b /vendor -b
/d -b /tombstones -b /efs -b /firmware-mdm -b /firmware -b /
system -b /res -b /data /usr/bin/octave
GNU Octave, version 3.6.2
Copyright (C) 2012 John W. Eaton and others.
This is free software; see the source code for copying conditions.
There is ABSOLUTELY NO WARRANTY; not even for MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  For details, type `warranty'.

Octave was configured for "arm-unknown-linux-gnueabi".

Additional information about Octave is available at http://www.octave.org.

Please contribute if you find this software useful.
For more information, visit http://www.octave.org/help-wanted.html

Read http://www.octave.org/bugs.html to learn how to submit bug reports.

For information about changes from previous versions, type `news'.

warning: X11 DISPLAY environment variable not set
Your home directory can be found at /storage/emulated/0/GNUOctave/home.
You can put .m files there or a .octaverc file there.
Add-on packages (com.octave.*) may be found on the Play Store.
octave:1>

**Comment by corbinlc** [comment]
I found a bug report from Cyanogenmod users related to the initial command for the Android Terminal Emulator (I have ATE built into my app) not working and it ended up being related to a new version of busybox and its use of resize.  So, I decided to isolate myself from the shell that the system ships with and any PATH setting outside of the octave fake chroot.  Please mess around with it some more and tell me if you run into anything odd.  I will too.  Want to make sure I am not breaking other people (I sadly don't have a verification sweet in place yet).
